
s3:
  bucket_name: restoration-monitoring
  upload_gjson: True


opt_api:
  opt_url: https://portal.opentopography.org/API/globaldem

tm_api:
  tm_auth_path: ../secrets.yaml #UPDATE
  tm_staging_url: https://api-staging.terramatch.org/research/v3/sitePolygons?  
  tm_prod_url: https://api.terramatch.org/research/v3/sitePolygons?

criteria:
  canopy_threshold: 40                                         # threshold for identifying open vs closed canopy projects
  cloud_thresh: 50                                             # threshold for identifying image quality
  off_nadir: 30                                                # number of degrees that the sensor varies from vertical
  sun_elevation: 30
  img_count: 1                                                 # threshold for identifying image availability
  baseline_range: [-365, 0]                                    # baseline window (1 year before plant start date)
  ev_range: [730, 1095]                                        # EV window (2 years after plant start date)
  drop_missing: False
  slope_thresh: 20
  rules: data/rule_template.csv

outfile:
  today: 06-18-2025
  cohort: c1               
  portfolio: ../data/portfolio_csvs/terrafund_approved_projects_202504021529.csv
  geojsons: ../data/geojsons/
  tm_response: ../data/tm_api_response/{cohort}_{today}.json
  ot_response: ../data/slope/slope_statistics_{cohort}_{today}.csv
  feats: ../data/tm_api_{cohort}_{today}.csv
  slope: ../data/slope/slope_{cohort}.csv
  feats_maxar_query: Users/jessica.ertel/github/maxar-tools/data/tm_api_c2_{today}.csv
  maxar_meta: ../data/imagery_availability/comb_img_availability_{cohort}_{today}.csv
  decision: ../data/dtree_output_{cohort}_{today}.csv

